apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogo-da-velha
  labels:
    app: jogo-da-velha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jogo-da-velha
  template:
    metadata:
      labels:
        app: jogo-da-velha
    spec:
      containers:
<<<<<<< HEAD
      - name: tic-tac-toe
        image: ghcr.io/jcom42/jun_cluster_devsecops:sha-ce066654dda4e0e5991b7797161e5db1554b74e1
=======
      - name: jogo-da-velha
        image: ghcr.io/jcom42/jun_cluster_devsecops:sha-944a2b91fc755762be52eb5a615439e9c0cedc61
>>>>>>> 38e4f6d (atualizado para 1 replicaset)
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.9"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: token2
